config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'
  root 'restaurants#index'

  get 'carts/show'
  get 'tags/:tag', to: 'restaurants#index', as: :tag

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'registrations' }

  resources :restaurants, only: [:index, :show] do
    resources :products, only: [:index, :show]
    resources :categories, only: [:index, :show]
  end

  resource :dashboard, only: [:show]

  namespace :dashboard do
    resources :restaurants, except: [:index, :destroy] do
      post :import
      resources :products
      resources :categories
      resources :roles
      resources :positions
      resources :tables
      resources :orders, only: [:index, :edit, :update]
      resources :order_items, only: [:index, :show, :update] do
        collection do
          get 'refresh_orders'
        end
      end
      resource :menus, only: [:show]
    end
  end

  resource :cart, only: [:show]

  resources :order_items, only: [:create, :update, :destroy]

  resources :orders do
    member do
      get :pay
    end
  end
end

app/controllers/dashboard/categories_controller.rb
# frozen_string_literal: true
class Dashboard::CategoriesController < ApplicationController
  load_and_authorize_resource find_by: :slug

  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = @restaurant.categories
    @categories = @categories.search(params[:search])
    @categories = @categories.page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @categories }
      format.js { render partial: 'index' }
    end
  end

  def show
    @products = @category.products.page(params[:page])
  end

  def new
    @category = @restaurant.categories.build
    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def edit
    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def create
    @category = @restaurant.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html do
          redirect_to dashboard_restaurant_categories_path(@restaurant),
                      notice: 'Category was successfully created.',
                      status: :created
        end
        format.js 
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html do
          redirect_to dashboard_restaurant_categories_path(@restaurant),
                      notice: 'Category was successfully updated.',
                      status: :ok
        end
        format.js
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_restaurant_categories_path(@restaurant), flash: { notice: 'Category was successfully destroyed.' } }
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end

  def set_category
    @category = @restaurant.categories.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :age_restriction, :available_all_day, :avatar, :index)
  end
end

app/controllers/dashboard/menus_controller.rb
# frozen_string_literal: true
class Dashboard::MenusController < ApplicationController
  before_action :authenticate_user!
  before_action :set_restaurant

  def show

  end

  def import
    logger.debug "STARTING TO IMPORT FILE IN MENUS CONTROLLER, THE FILE IS #{params[:file]}"
    upload = params[:file]
    File.open(Rails.root.join('tmp/menu_import', upload.original_filename), 'wb') do |file|
      file.write(upload.read)
    end

    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
    MenuImportWorker.perform_async(@restaurant.id, upload.original_filename)
    Rails.logger.info upload.original_filename
    redirect_to dashboard_restaurant_path(@restaurant),
                notice: 'File was uploaded successfully and is being processed.'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end
end

app/controllers/dashboard/order_items_controller.rb
class Dashboard::OrderItemsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :set_order_item, only: [:update, :show]

  def index
    session[:order_status] = params[:order_status] || session[:order_status]
    @items = @restaurant.order_items.where(status: session[:order_status]).order(:updated_at).page(params[:page]).per(15)
    respond_to do |format|
      format.html {}
      format.js { @partial_name = "element_row_#{session[:order_status]}" }
    end
  end

  def show

  end

  def update
    if params[:order_action] == "reported"
      @order_item.order.user.reset_rating
      @order_item.order.order_items.update_all(status: 'reported')
    else
      @order_item.next_status
    end
    
    @order_item.order.user.add_rating if @order_item.status == "delivered"
    @items = @restaurant.order_items.where(status: session[:order_status]).page(params[:page])

    respond_to do |format|
      format.js
      format.html { redirect_to dashboard_restaurant_order_item_path(@restaurant, @order_item) }
    end
  end

  def refresh_orders
    @items = @restaurant.order_items.where(status: session[:order_status]).order(:updated_at).page(params[:page]).per(15)
    @partial_name = "element_row_#{session[:order_status]}"
    respond_to do |format|
        format.js 
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end

  def set_order_item
    @order_item = @restaurant.order_items.find(params[:id])
  end
end

app/controllers/dashboard/positions_controller.rb
# frozen_string_literal: true
class Dashboard::PositionsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :set_position, only: [:show, :edit, :destroy]

  def index
    @positions = @restaurant.positions
    @positions = @positions.search(params[:search])
    @positions = @positions.page(params[:page])
    
    respond_to do |format|
      format.html
      format.json { render json: @positions }
      format.js { render partial: 'index' }
    end
  end

  def show
  end

  def new
    @position = @restaurant.positions.build
    @roles = @restaurant.roles

    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def edit
    @roles = @restaurant.roles
    @editing = true

    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def create
    @employee = User.find_by(email: params[:email])
    params[:position][:user_id] = @employee.id

    @position = @restaurant.positions.new(position_params)

    respond_to do |format|
      if @position.save
        format.html do
          redirect_to dashboard_restaurant_positions_path(@restaurant),
                      notice: 'Employee was successfully added.',
                      status: :created
        end
        format.js
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html do
          redirect_to dashboard_restaurant_position_path(@restaurant, @position),
                      notice: 'Employee status was successfully updated.',
                      status: :ok
        end
        format.js
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_restaurant_positions_path(@restaurant), flash: { notice: 'Employee was successfully removed.' } }
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end

  def set_position
    @position = @restaurant.positions.find(params[:id])
  end

  def position_params
    params.require(:position).permit(:role_id, :user_id)
  end
end

app/controllers/dashboard/products_controller.rb
# frozen_string_literal: true
class Dashboard::ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :set_product, only: [:show, :update, :edit, :destroy]

  def index
    @products = @restaurant.products.search(params[:search])
                           .page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @products }
      format.js { render partial: 'index' }
    end
  end

  def show
  end

  def new
    @product = @restaurant.products.build
    @categories = @restaurant.categories

    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def edit
    @categories = @restaurant.categories

    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def create
    @product = @restaurant.products.new(product_params)

    respond_to do |format|
      if @product.save
        @products = @restaurant.products.page(params[:page])
        format.html do
          redirect_to dashboard_restaurant_products_path(@restaurant),
                      notice: 'Product was successfully added.',
                      status: :created
        end
        format.js 
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html do
          redirect_to dashboard_restaurant_products_path(@restaurant),
                      notice: 'Product was successfully updated.',
                      status: :ok
        end
        format.js
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to @restaurant, flash: { notice: 'Product was successfully destroyed.' } }
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end

  def set_product
    @product = @restaurant.products.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :short_description, :description, :price,
                                    :category_id, :avatar, :tag_list, :allergen_list, :weight,
                                    sizes_attributes: [:id, :name, :price, :description, :product_id, :_destroy],
                                    groups_attributes: [:id, :name, :maximum, :product_id, :_destroy,
                                                        options_attributes: [:id, :name, :group_id, :price, :_destroy]])
  end
end

app/controllers/dashboard/restaurants_controller.rb
# frozen_string_literal: true
class Dashboard::RestaurantsController < ApplicationController
  load_and_authorize_resource find_by: :slug
  before_action :authenticate_user!
  before_action :set_restaurant, except: [:show, :new, :edit, :update, :import]

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html do
          redirect_to edit_dashboard_restaurant_path(@restaurant),
                      flash: { notice: 'Restaurant was successfully created.' }
        end
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    upload = params[:file]
    File.open(Rails.root.join('tmp/menu_import', upload.original_filename), 'wb') do |file|
      file.write(upload.read)
    end
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
    MenuImportWorker.perform_async(@restaurant.id, upload.original_filename)
    redirect_to dashboard_restaurant_path(@restaurant),
                notice: 'File was uploaded successfully and is being processed.'
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to edit_dashboard_restaurant_path(@restaurant), flash: { notice: 'Restaurant was successfully updated.' } }
        format.json { render :edit, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :tag_list, :country, :address, :description, :phone_number, :wifipassword,:avg_meal_price, 
                                      :staff_count, :facebook_link,
                                      :twitter_link, :available_payment,
                                      :sells_online,
                                      :restaurant_avatar, language_ids: [],
                                      working_times_attributes: [:id, :from_time, :to_time, :from_day, :to_day, :restaurant_id, :_destroy],
                                      images_attributes: [:id, :pic, :restaurant_id, :_destroy])
  end
end

app/controllers/dashboard/roles_controller.rb
# frozen_string_literal: true
class Dashboard::RolesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :set_role, except: [:index, :create, :new]

  def index
    @roles = @restaurant.roles
    @roles = @roles.search(params[:search]).page(params[:page])
    
    respond_to do |format|
      format.html
      format.json { render json: @roles }
      format.js { render partial: 'index' }
    end
  end

  def show
  end

  def new
    @role = @restaurant.roles.build

    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def edit
    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def create
    @role = @restaurant.roles.new(role_params)

    respond_to do |format|
      if @role.save
        format.html do
          redirect_to dashboard_restaurant_roles_path(@restaurant),
                      notice: 'Role was successfully created.',
                      status: :created
        end
        format.js
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html do
          redirect_to dashboard_restaurant_roles_path(@restaurant),
                      notice: 'Role was successfully updated.',
                      status: :ok
        end
        format.js
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    respond_to do |format|
      @role.destroy
      format.html { redirect_to dashboard_restaurant_roles_path(@restaurant) }
      format.js
    end
  end

  private

  def set_role
    @role = @restaurant.roles.find(params[:id])
  end

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end

  def role_params
    params.require(:role).permit(:name, :restaurant_id,
                                 permission_ids: [])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  include DashboardsHelper

  def show
    render 'dashboard/show'
  end
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true
module DashboardsHelper
  def should_see?(obj)
    (can? :read, obj) || (can? :edit, obj) || (can? :create, obj) || (can? :update, obj) || (can? :destroy, obj)
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true
module ProductsHelper
  def size_price(product, size)
    formatted_price(product.price + size.price, product.restaurant)
  end

  def product_price(product)
    if product.sizes.any?
      (t 'product.price-from').to_s + formatted_price(product.price, product.restaurant)
    else
      formatted_price(product.price, @restaurant)
    end
  end

  def common_alergens(prod, user)
    if prod && user 
      allergens = prod.allergen_list & user.allergen_list
      (t 'product.contains').to_s + allergens.to_sentence if allergens.any?
    end
  end
end

app/views/dashboard/products/_element_form.slim
= simple_form_for([:dashboard, @restaurant, @product], remote: true, 
  html: { multipart: true }, authenticity_token: true) do |f|
  .modal-header
    = (t 'dashboard.product-form-title') + @restaurant.name
    button.close aria-label="Close" data-dismiss="modal" type="button"
      span aria-hidden="true"  &times;

  .modal-body
    = render 'layouts/error_messages', object: @product
    - if @product.avatar?
      = image_tag @product.avatar.url(:small), class: "center-block img-rounded"
    = f.input :avatar, as: :file
    = f.input :name, hint: (I18n.locale == :en ? "" : "en: #{I18n.with_locale(:en) {f.object.name}}")
    = f.input :short_description, hint: (I18n.locale == :en ? "" : "en: #{I18n.with_locale(:en) {f.object.short_description}}")
    = f.input :description, hint: (I18n.locale == :en ? "" : "en: #{I18n.with_locale(:en) {f.object.description}}")
    = f.input :weight
    = f.input :price
    = f.input :ready
    = f.input :allergen_list, input_html: {value: @product.allergen_list.to_s}
    = f.association :category, collection: @categories, prompt: "Choose a category", include_blank: false

    .product_sizes
      = f.simple_fields_for :sizes do |size|
        = render 'size_fields', f: size
      .links
        = link_to_add_association f, :sizes

    .product_option_groups
      = f.simple_fields_for :groups do |group|
        = render 'group_fields', f: group
      .links
        = link_to_add_association f, :groups


        
  .modal-footer     
    = f.button :submit, disable_with: "#{t "simple_form.please-wait"}"

app/views/dashboard/products/_element_row.html.slim
tr
  td = product.name
  td = product.category.name
  td 
    .show
      = link_to "", dashboard_restaurant_product_path(@restaurant, product),
        class: "glyphicon glyphicon-info-sign"
    .edit
      = link_to "", edit_dashboard_restaurant_product_path(@restaurant, product),
        class: "glyphicon glyphicon-pencil", data: { target: '#element-form', toggle: 'modal', remote: true}
    .destroy
      = link_to "", dashboard_restaurant_product_path(@restaurant, product),
        {confirm: "Are you sure?", method: :delete, remote: true, class: "glyphicon glyphicon-trash" }

app/views/dashboard/products/_group_fields.html.slim
.nested-fields
  = f.input :name, hint: (I18n.locale == :en ? "" : "en: #{I18n.with_locale(:en) {f.object.name}}")
  = f.input :maximum
  = f.input :_destroy, as: :hidden
  = link_to_remove_association f

  .product_options
    = f.simple_fields_for :options do |option|
      = render 'option_fields', f: option
    .links
      = link_to_add_association f, :options

app/views/dashboard/products/_option_fields.html.slim
.nested-fields
  = f.input :name, hint: (I18n.locale == :en ? "" : "en: #{I18n.with_locale(:en) {f.object.name}}")
  = f.input :price
  = f.input :_destroy, as: :hidden
  = link_to_remove_association f

app/views/dashboard/products/_product.html.slim
tr id="product-#{product.id}"
  td = product.name
  td = product.category.name
  td 
    .show
      = link_to "", dashboard_restaurant_product_path(@restaurant, product),
        class: "glyphicon glyphicon-info-sign"
    .edit
      = link_to "", edit_dashboard_restaurant_product_path(@restaurant, product),
        class: "glyphicon glyphicon-pencil", data: { target: '#element-form', toggle: 'modal', remote: true}
    .destroy
      = link_to "", dashboard_restaurant_product_path(@restaurant, product),
        {confirm: "Are you sure?", method: :delete, remote: true, class: "glyphicon glyphicon-trash" }

app/views/dashboard/products/_product_option_fields.html.slim
.nested-fields
  = f.input :name, placeholder: "sauces, flavours, etc."
  = f.input :_destroy, as: :hidden
  = link_to_remove_association "remove option", f

app/views/dashboard/products/_product_size_fields.html.slim
.nested-fields
  = f.input :name, placeholder: "e.g. small, medium, large"
  = f.input :price
  = f.input :short_description
  = f.input :_destroy, as: :hidden
  = link_to_remove_association "remove size", f

app/views/dashboard/products/_search_results.html.slim
- if @products.blank?
  p.text-center
    = t "search.no-results"
- else
  table#products.table.table-striped
    thead
      tr
        th = t 'dashboard.name'
        th = t 'dashboard.categories'
        th = t 'dashboard.actions'
    tbody
      = render partial: "product", collection: @products, as: :product
  = paginate @products, theme: 'twitter-bootstrap-3'

app/views/dashboard/products/_size_fields.html.slim
.nested-fields
  = f.input :name, placeholder: "e.g. small, medium, large", 
                   hint: (I18n.locale == :en ? "" : "en: #{I18n.with_locale(:en) {f.object.name}}")
  = f.input :price
  = f.input :description, hint: (I18n.locale == :en ? "" : "en: #{I18n.with_locale(:en) {f.object.description}}")
  = f.input :_destroy, as: :hidden
  = link_to_remove_association f

app/views/dashboard/products/create.js.erb
$('.search-results').html("<%= escape_javascript (render partial: 'search_results') %>");
$('#element-form').modal('hide');
$(".alert").fadeTo(2000, 500).slideUp(500, function(){
  $(".alert").alert('close');
});

app/views/dashboard/products/destroy.js.erb
$('#product-<%= @product.id %>').fadeOut(500);

app/views/dashboard/products/index.html.slim
= render 'layouts/dashboard/dashboard_navbar'
.container.container-white.col-xs-12.col-sm-8.col-sm-offset-1.dashboard-main-window
  h3 = t 'dashboard.product-index-title'

  .search-form.col-xs-12
    = form_tag dashboard_restaurant_products_path(@restaurant),
               method: :get, remote: true do
      .input-group
        = text_field_tag :search, params[:search],
                         class: "form-control input",
                         placeholder: "Search by product name"
        span.input-group-btn
          = button_tag(type: 'submit', class: "btn btn-info btn") do
            i class="glyphicon glyphicon-search"

  .search-results
    = render partial: "search_results"

  .new-element.col-xs-6
    = link_to (t 'button.add-product'), new_dashboard_restaurant_product_path(@restaurant), class: 'btn btn-primary btn-lg',
      data: { target: '#element-form', toggle: 'modal' , remote: true}
    #element-form.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
      .modal-dialog role="document"
        .modal-content
          | Please wait ...
    = link_to " or upload your menu", dashboard_restaurant_menus_path(@restaurant)

app/views/dashboard/products/show.html.slim
= render 'layouts/dashboard/dashboard_navbar'

.container.container-white.col-xs-12.col-sm-8.col-sm-offset-1.dashboard-main-window
  h3 = @product.name

  

app/views/dashboard/products/update.js.erb
<% if @product.errors.any? %>
 $('.modal-content').html("<%= j(render partial: 'element_form').html_safe%>")
<% else %>
  $('#element-form').modal('hide');
  $('#product-<%= @product.id %>').fadeOut(1000);
  $('#products').prepend($("<%= j render @product %>").fadeIn('slow'));
<% end %>