config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'
  root 'restaurants#index'

  get 'carts/show'
  get 'tags/:tag', to: 'restaurants#index', as: :tag

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'registrations' }

  resources :restaurants, only: [:index, :show] do
    resources :products, only: [:index, :show]
    resources :categories, only: [:index, :show]
  end

  resource :dashboard, only: [:show]

  namespace :dashboard do
    resources :restaurants, except: [:index, :destroy] do
      post :import
      resources :products
      resources :categories
      resources :roles
      resources :positions
      resources :tables
      resources :orders, only: [:index, :edit, :update]
      resources :order_items, only: [:index, :show, :update] do
        collection do
          get 'refresh_orders'
        end
      end
      resource :menus, only: [:show]
    end
  end

  resource :cart, only: [:show]

  resources :order_items, only: [:create, :update, :destroy]

  resources :orders do
    member do
      get :pay
    end
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @order_items = current_order.order_items.order('created_at')

    @restaurant = current_order.restaurant
    add_breadcrumb @restaurant.name, restaurant_path(@restaurant), title: "Back to the restaurant"
    add_breadcrumb "menu", restaurant_path(@restaurant, menu: "open"), title: "Back to menu"
    add_breadcrumb "cart"
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true
module CartsHelper
end

app/views/layouts/cart/_buy_button.html.slim
- if current_order.fulfils_requirements?

  = link_to pay_order_path(current_order), class: "btn col-xs-12 pay-button", 
    remote: (controller_name == 'restaurants' ? "true" : "false") , data: {confirm: "Send order to restaurant?"}
      b = formatted_price(current_order.subtotal, current_order.restaurant)


- else
  = link_to root_path, class: "btn col-xs-12 pay-button disabled"
    b.col-xs-12 = formatted_price(current_order.subtotal, current_order.restaurant)

app/views/layouts/cart/_cart.html.slim
- if current_user && @restaurant && current_order.restaurant == @restaurant
  .container.col-md-4.container-white.compact-cart.hidden-xs.hidden-sm
    h3.col-xs-12.text-center #{t 'cart.cart'}
    #order-items
      = render partial: "carts/order_item", collection: current_order.order_items.order('created_at'), as: :order_item
    .buy-button.col-md-4
      = render partial: 'layouts/cart/buy_button'
  