config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'
  root 'restaurants#index'

  get 'carts/show'
  get 'tags/:tag', to: 'restaurants#index', as: :tag

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'registrations' }

  resources :restaurants, only: [:index, :show] do
    resources :products, only: [:index, :show]
    resources :categories, only: [:index, :show]
  end

  resource :dashboard, only: [:show]

  namespace :dashboard do
    resources :restaurants, except: [:index, :destroy] do
      post :import
      resources :products
      resources :categories
      resources :roles
      resources :positions
      resources :tables
      resources :orders, only: [:index, :edit, :update]
      resources :order_items, only: [:index, :show, :update] do
        collection do
          get 'refresh_orders'
        end
      end
      resource :menus, only: [:show]
    end
  end

  resource :cart, only: [:show]

  resources :order_items, only: [:create, :update, :destroy]

  resources :orders do
    member do
      get :pay
    end
  end
end

app/controllers/dashboard/categories_controller.rb
# frozen_string_literal: true
class Dashboard::CategoriesController < ApplicationController
  load_and_authorize_resource find_by: :slug

  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = @restaurant.categories
    @categories = @categories.search(params[:search])
    @categories = @categories.page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @categories }
      format.js { render partial: 'index' }
    end
  end

  def show
    @products = @category.products.page(params[:page])
  end

  def new
    @category = @restaurant.categories.build
    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def edit
    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def create
    @category = @restaurant.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html do
          redirect_to dashboard_restaurant_categories_path(@restaurant),
                      notice: 'Category was successfully created.',
                      status: :created
        end
        format.js 
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html do
          redirect_to dashboard_restaurant_categories_path(@restaurant),
                      notice: 'Category was successfully updated.',
                      status: :ok
        end
        format.js
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_restaurant_categories_path(@restaurant), flash: { notice: 'Category was successfully destroyed.' } }
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end

  def set_category
    @category = @restaurant.categories.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :age_restriction, :available_all_day, :avatar, :index)
  end
end

app/controllers/dashboard/menus_controller.rb
# frozen_string_literal: true
class Dashboard::MenusController < ApplicationController
  before_action :authenticate_user!
  before_action :set_restaurant

  def show

  end

  def import
    logger.debug "STARTING TO IMPORT FILE IN MENUS CONTROLLER, THE FILE IS #{params[:file]}"
    upload = params[:file]
    File.open(Rails.root.join('tmp/menu_import', upload.original_filename), 'wb') do |file|
      file.write(upload.read)
    end

    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
    MenuImportWorker.perform_async(@restaurant.id, upload.original_filename)
    Rails.logger.info upload.original_filename
    redirect_to dashboard_restaurant_path(@restaurant),
                notice: 'File was uploaded successfully and is being processed.'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end
end

app/controllers/dashboard/order_items_controller.rb
class Dashboard::OrderItemsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :set_order_item, only: [:update, :show]

  def index
    session[:order_status] = params[:order_status] || session[:order_status]
    @items = @restaurant.order_items.where(status: session[:order_status]).order(:updated_at).page(params[:page]).per(15)
    respond_to do |format|
      format.html {}
      format.js { @partial_name = "element_row_#{session[:order_status]}" }
    end
  end

  def show

  end

  def update
    if params[:order_action] == "reported"
      @order_item.order.user.reset_rating
      @order_item.order.order_items.update_all(status: 'reported')
    else
      @order_item.next_status
    end
    
    @order_item.order.user.add_rating if @order_item.status == "delivered"
    @items = @restaurant.order_items.where(status: session[:order_status]).page(params[:page])

    respond_to do |format|
      format.js
      format.html { redirect_to dashboard_restaurant_order_item_path(@restaurant, @order_item) }
    end
  end

  def refresh_orders
    @items = @restaurant.order_items.where(status: session[:order_status]).order(:updated_at).page(params[:page]).per(15)
    @partial_name = "element_row_#{session[:order_status]}"
    respond_to do |format|
        format.js 
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end

  def set_order_item
    @order_item = @restaurant.order_items.find(params[:id])
  end
end

app/controllers/dashboard/positions_controller.rb
# frozen_string_literal: true
class Dashboard::PositionsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :set_position, only: [:show, :edit, :destroy]

  def index
    @positions = @restaurant.positions
    @positions = @positions.search(params[:search])
    @positions = @positions.page(params[:page])
    
    respond_to do |format|
      format.html
      format.json { render json: @positions }
      format.js { render partial: 'index' }
    end
  end

  def show
  end

  def new
    @position = @restaurant.positions.build
    @roles = @restaurant.roles

    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def edit
    @roles = @restaurant.roles
    @editing = true

    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def create
    @employee = User.find_by(email: params[:email])
    params[:position][:user_id] = @employee.id

    @position = @restaurant.positions.new(position_params)

    respond_to do |format|
      if @position.save
        format.html do
          redirect_to dashboard_restaurant_positions_path(@restaurant),
                      notice: 'Employee was successfully added.',
                      status: :created
        end
        format.js
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html do
          redirect_to dashboard_restaurant_position_path(@restaurant, @position),
                      notice: 'Employee status was successfully updated.',
                      status: :ok
        end
        format.js
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_restaurant_positions_path(@restaurant), flash: { notice: 'Employee was successfully removed.' } }
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end

  def set_position
    @position = @restaurant.positions.find(params[:id])
  end

  def position_params
    params.require(:position).permit(:role_id, :user_id)
  end
end

app/controllers/dashboard/products_controller.rb
# frozen_string_literal: true
class Dashboard::ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :set_product, only: [:show, :update, :edit, :destroy]

  def index
    @products = @restaurant.products.search(params[:search])
                           .page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @products }
      format.js { render partial: 'index' }
    end
  end

  def show
  end

  def new
    @product = @restaurant.products.build
    @categories = @restaurant.categories

    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def edit
    @categories = @restaurant.categories

    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def create
    @product = @restaurant.products.new(product_params)

    respond_to do |format|
      if @product.save
        @products = @restaurant.products.page(params[:page])
        format.html do
          redirect_to dashboard_restaurant_products_path(@restaurant),
                      notice: 'Product was successfully added.',
                      status: :created
        end
        format.js 
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html do
          redirect_to dashboard_restaurant_products_path(@restaurant),
                      notice: 'Product was successfully updated.',
                      status: :ok
        end
        format.js
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to @restaurant, flash: { notice: 'Product was successfully destroyed.' } }
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end

  def set_product
    @product = @restaurant.products.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :short_description, :description, :price,
                                    :category_id, :avatar, :tag_list, :allergen_list, :weight,
                                    sizes_attributes: [:id, :name, :price, :description, :product_id, :_destroy],
                                    groups_attributes: [:id, :name, :maximum, :product_id, :_destroy,
                                                        options_attributes: [:id, :name, :group_id, :price, :_destroy]])
  end
end

app/controllers/dashboard/restaurants_controller.rb
# frozen_string_literal: true
class Dashboard::RestaurantsController < ApplicationController
  load_and_authorize_resource find_by: :slug
  before_action :authenticate_user!
  before_action :set_restaurant, except: [:show, :new, :edit, :update, :import]

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html do
          redirect_to edit_dashboard_restaurant_path(@restaurant),
                      flash: { notice: 'Restaurant was successfully created.' }
        end
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    upload = params[:file]
    File.open(Rails.root.join('tmp/menu_import', upload.original_filename), 'wb') do |file|
      file.write(upload.read)
    end
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
    MenuImportWorker.perform_async(@restaurant.id, upload.original_filename)
    redirect_to dashboard_restaurant_path(@restaurant),
                notice: 'File was uploaded successfully and is being processed.'
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to edit_dashboard_restaurant_path(@restaurant), flash: { notice: 'Restaurant was successfully updated.' } }
        format.json { render :edit, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :tag_list, :country, :address, :description, :phone_number, :wifipassword,:avg_meal_price, 
                                      :staff_count, :facebook_link,
                                      :twitter_link, :available_payment,
                                      :sells_online,
                                      :restaurant_avatar, language_ids: [],
                                      working_times_attributes: [:id, :from_time, :to_time, :from_day, :to_day, :restaurant_id, :_destroy],
                                      images_attributes: [:id, :pic, :restaurant_id, :_destroy])
  end
end

app/controllers/dashboard/roles_controller.rb
# frozen_string_literal: true
class Dashboard::RolesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_restaurant
  before_action :set_role, except: [:index, :create, :new]

  def index
    @roles = @restaurant.roles
    @roles = @roles.search(params[:search]).page(params[:page])
    
    respond_to do |format|
      format.html
      format.json { render json: @roles }
      format.js { render partial: 'index' }
    end
  end

  def show
  end

  def new
    @role = @restaurant.roles.build

    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def edit
    respond_to do |format|
      format.js { render partial: 'form.js.coffee' }
    end
  end

  def create
    @role = @restaurant.roles.new(role_params)

    respond_to do |format|
      if @role.save
        format.html do
          redirect_to dashboard_restaurant_roles_path(@restaurant),
                      notice: 'Role was successfully created.',
                      status: :created
        end
        format.js
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html do
          redirect_to dashboard_restaurant_roles_path(@restaurant),
                      notice: 'Role was successfully updated.',
                      status: :ok
        end
        format.js
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    respond_to do |format|
      @role.destroy
      format.html { redirect_to dashboard_restaurant_roles_path(@restaurant) }
      format.js
    end
  end

  private

  def set_role
    @role = @restaurant.roles.find(params[:id])
  end

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end

  def role_params
    params.require(:role).permit(:name, :restaurant_id,
                                 permission_ids: [])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  include DashboardsHelper

  def show
    render 'dashboard/show'
  end
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true
module DashboardsHelper
  def should_see?(obj)
    (can? :read, obj) || (can? :edit, obj) || (can? :create, obj) || (can? :update, obj) || (can? :destroy, obj)
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper

  def order_exists?
    current_order.restaurant_id == @restaurant.id
  end

  # Verifies that the order is valid
  def current_order_valid?
    current_order.table_id || current_order.address
  end

  # Adds the order item to the current_order
  def add_item
    current_order.order_items << @order_item
    current_order.save
  end

  def option_names(item)
    names = []
    item.options.each do |opt|
      names << opt.name
    end
    names
  end

  def delivery_destination(item)
    ((t 'order.table') + " " + item.order.table_number.to_s) unless item.order.table_number.nil?
  end
end

app/views/dashboard/order_items/_element_row_delivered.html.slim
tr.item class="row-#{item.id}"
  td.product-name.col-xs-5
    h4 = item.product.name
    h5 = item.size.try(:name)
    h5 = option_names(item).to_sentence
  td.col-xs-5
    .username.col-xs-12 = link_to dashboard_restaurant_order_item_path(@restaurant, item) do 
      b #{item.order.user.try(:name)} (#{item.order.user.rating} rating)
    .time-ago.col-xs-6 = time_ago_in_words(item.delivered_at)
    .destination.col-xs-6 = delivery_destination(item)
  td.actions.col-xs-2
    = link_to "Show", dashboard_restaurant_order_item_path(@restaurant, item),
      class: "btn btn-default pull-right"

app/views/dashboard/order_items/_element_row_ready.html.slim
tr.item class="row-#{item.id} #{item.order.user.trustworthy? ? '' : 'confirm-order'}"
  td.product-name.col-xs-5
    h4 = item.product.name
    h5 = item.size.try(:name)
    h5 = option_names(item).to_sentence
  td.col-xs-5
    .username.col-xs-12 = link_to dashboard_restaurant_order_item_path(@restaurant, item) do 
      b #{item.order.user.try(:name)} (#{item.order.user.rating} rating)
    .time-ago.col-xs-6 = time_ago_in_words(item.ready_at)
    .destination.col-xs-6 = delivery_destination(item)
  td.actions.col-xs-2
    = link_to dashboard_restaurant_order_item_path(@restaurant, item),
      {method: :patch, remote: true, class: "btn btn-success pull-right" } do
      i.fa.fa-check
.col-xs-12.demands = item.try(:demands)

app/views/dashboard/order_items/_element_row_unready.html.slim
tr.item class="row-#{item.id} #{item.order.user.trustworthy? ? '' : 'confirm-order'}"
  td.product-name.col-xs-5
    h4 = item.product.name
    h5 = item.size.try(:name)
    h5 = option_names(item).to_sentence
    h4.demands = item.try(:demands)
  td.col-xs-5
    .username.col-xs-12 = link_to dashboard_restaurant_order_item_path(@restaurant, item) do 
      b #{item.order.user.try(:name)} (#{item.order.user.rating} rating)
    .time-ago.col-xs-6 = time_ago_in_words(item.received_at)
    .destination.col-xs-6 = delivery_destination(item)
  td.col-xs-2.actions 
    = link_to dashboard_restaurant_order_item_path(@restaurant, item),
      {method: :patch, remote: true, class: "btn btn-success pull-right" } do 
      i.fa.fa-check

app/views/dashboard/order_items/_table_delivered.html.slim
h2.text-center Listing delivered orders
table#items.table.table-striped.items.col-xs-12
  tbody.page
    = yield
p
  = paginate @items

app/views/dashboard/order_items/_table_ready.html.slim
h2.text-center Listing ready orders
table#items.table.table-striped.items.col-xs-12
  tbody.page
    = yield
p
  = paginate @items

app/views/dashboard/order_items/_table_unready.html.slim
h2.text-center Listing unready orders
table#items.table.table-striped.col-xs-12
  tbody.page
    = yield
p
  = paginate @items

app/views/dashboard/order_items/index.html.slim
= render 'layouts/dashboard/dashboard_navbar'

.container.container-white.order-items.col-xs-12.col-sm-11.col-sm-offset-1.col-md-8.col-md-offset-1.col-lg-6.col-lg-offset-1.dashboard-main-window
  = render layout: "table_#{session[:order_status]}" do
    = render partial: "element_row_#{session[:order_status]}", collection: @items, as: :item




  javascript:
      setInterval(function() {
        $.ajax({
          url: '#{refresh_orders_dashboard_restaurant_order_items_path(@restaurant)}',
          type: 'GET',
          data: {},
          dataType: 'script'
        });
      }, 5000);

app/views/dashboard/order_items/index.js.erb
$("<%=j render partial: @partial_name, collection: @items, as: :item %>")
  .appendTo($(".infinite-table table"));

<% if @items.last_page? %>
  $('.pagination').html("You reached the end!");
<% else %>
  $('.pagination')
    .html("<%=j link_to_next_page(@items, 'Next Page', remote: true) %>");
<% end %>

app/views/dashboard/order_items/refresh_orders.js.erb
$('.dashboard-main-window tbody').html("<%=j render partial: @partial_name, collection: @items, as: :item %>");

app/views/dashboard/order_items/show.html.slim
= render 'layouts/dashboard/dashboard_navbar'

.container.container-white.col-xs-12.col-sm-8.col-sm-offset-1.dashboard-main-window
  h2.text-center Showing order items by this user
  hr
  .col-xs-12.col-md-6.col-md-offset-3.text-left
    .ordered-items.col-xs-12
      - @order_item.order.order_items.each do |item| 
        .item.col-xs-12.col-md-4 style="border:1px solid rgb(240,240,240);"
          h4 = item.product.name
          h5 = item.size.try(:name)
          h5 = option_names(item).to_sentence
          h4 Status: #{item.status}
    span style="padding:30px;"
    h4 Ordered by: #{@order_item.order.user.name}
    h4 Tel. number: #{@order_item.order.user.try(:phone_number)}
    h4 Rating: #{@order_item.order.user.rating}
    hr
    - if @order_item.order.user.trustworthy?
      = link_to "Report user for incorrect order and reset his/her rating", 
        dashboard_restaurant_order_item_path(@restaurant, @order_item, order_action: 'reported'),
      {method: :patch, class: "btn btn-danger" }
    - else
      .btn.btn-info style="font-size:20px;" This user does not have enough rating to be reported

app/views/dashboard/order_items/update.js.erb
$(".row-<%= @order_item.id %>").remove();